[tool.poetry]
name = "pypfopt"
version = "0.3.1"
description = "Financial portfolio optimisation in python"
authors = ["Robert Andrew Martin <martin.robertandrew@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.4"
atomicwrites = "^=1.1.5"
attrs = "^=18.1.0"
more-itertools = "^=4.2.0"
noisyopt = "^=0.2.2"
numpy = "^=1.14.3"
pluggy = "^=0.6.0"
pulp = "^=1.6.9"
py = "^=1.5.3"
python-dateutil = "^=2.7.3"
pytz = "^=2018.4"
scipy = "^=1.1.0"
six = "^=1.11.0"
pytest = "^4.6"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
flake8 = "^3.7"
black = {version = "^18.9b0", python = "^3.6"}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
